apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-time-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-time
  template:
    metadata:
      labels:
        app: go-time
    spec:
      containers:
        - image: go-time:latest
          name: go-time
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: "150m"
            limits:
              cpu: "200m"