apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: go-time-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-time
  type: LoadBalancer
status:
  loadBalancer: {}
